// Code generated by ent, DO NOT EDIT.

package userachievement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the userachievement type in the database.
	Label = "user_achievement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAchievementID holds the string denoting the achievement_id field in the database.
	FieldAchievementID = "achievement_id"
	// FieldUnlockedAt holds the string denoting the unlocked_at field in the database.
	FieldUnlockedAt = "unlocked_at"
	// FieldProgressData holds the string denoting the progress_data field in the database.
	FieldProgressData = "progress_data"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAchievement holds the string denoting the achievement edge name in mutations.
	EdgeAchievement = "achievement"
	// Table holds the table name of the userachievement in the database.
	Table = "user_achievements"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_achievements"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// AchievementTable is the table that holds the achievement relation/edge.
	AchievementTable = "user_achievements"
	// AchievementInverseTable is the table name for the Achievement entity.
	// It exists in this package in order to avoid circular dependency with the "achievement" package.
	AchievementInverseTable = "achievements"
	// AchievementColumn is the table column denoting the achievement relation/edge.
	AchievementColumn = "achievement_id"
)

// Columns holds all SQL columns for userachievement fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldAchievementID,
	FieldUnlockedAt,
	FieldProgressData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultUnlockedAt holds the default value on creation for the "unlocked_at" field.
	DefaultUnlockedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the UserAchievement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAchievementID orders the results by the achievement_id field.
func ByAchievementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAchievementID, opts...).ToFunc()
}

// ByUnlockedAt orders the results by the unlocked_at field.
func ByUnlockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnlockedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAchievementField orders the results by achievement field.
func ByAchievementField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAchievementStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAchievementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AchievementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AchievementTable, AchievementColumn),
	)
}
