// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/music"
	"github.com/witchs-lounge_backend/ent/stage"
)

// Stage is the model entity for the Stage schema.
type Stage struct {
	config `json:"-"`
	// ID of the ent.
	// Global custom UUID ID
	ID uuid.UUID `json:"id,omitempty"`
	// Created time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 음악 ID
	MusicID uuid.UUID `json:"music_id,omitempty"`
	// 난이도 이름 (Easy, Normal, Hard, Expert)
	LevelName string `json:"level_name,omitempty"`
	// 난이도 수치 (1-10)
	Difficulty int `json:"difficulty,omitempty"`
	// 채보 파일 경로
	LevelAddress string `json:"level_address,omitempty"`
	// 난이도별 재킷 이미지 경로
	JacketAddress string `json:"jacket_address,omitempty"`
	// 총 노트 수
	TotalNotes int `json:"total_notes,omitempty"`
	// 최대 콤보
	MaxCombo int `json:"max_combo,omitempty"`
	// 활성 여부
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StageQuery when eager-loading is set.
	Edges        StageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StageEdges holds the relations/edges for other nodes in the graph.
type StageEdges struct {
	// Music holds the value of the music edge.
	Music *Music `json:"music,omitempty"`
	// Records holds the value of the records edge.
	Records []*Record `json:"records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MusicOrErr returns the Music value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StageEdges) MusicOrErr() (*Music, error) {
	if e.Music != nil {
		return e.Music, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: music.Label}
	}
	return nil, &NotLoadedError{edge: "music"}
}

// RecordsOrErr returns the Records value or an error if the edge
// was not loaded in eager-loading.
func (e StageEdges) RecordsOrErr() ([]*Record, error) {
	if e.loadedTypes[1] {
		return e.Records, nil
	}
	return nil, &NotLoadedError{edge: "records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Stage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stage.FieldIsActive:
			values[i] = new(sql.NullBool)
		case stage.FieldDifficulty, stage.FieldTotalNotes, stage.FieldMaxCombo:
			values[i] = new(sql.NullInt64)
		case stage.FieldLevelName, stage.FieldLevelAddress, stage.FieldJacketAddress:
			values[i] = new(sql.NullString)
		case stage.FieldCreatedAt, stage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case stage.FieldID, stage.FieldMusicID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Stage fields.
func (s *Stage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				s.ID = *value
			}
		case stage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case stage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		case stage.FieldMusicID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field music_id", values[i])
			} else if value != nil {
				s.MusicID = *value
			}
		case stage.FieldLevelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level_name", values[i])
			} else if value.Valid {
				s.LevelName = value.String
			}
		case stage.FieldDifficulty:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field difficulty", values[i])
			} else if value.Valid {
				s.Difficulty = int(value.Int64)
			}
		case stage.FieldLevelAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level_address", values[i])
			} else if value.Valid {
				s.LevelAddress = value.String
			}
		case stage.FieldJacketAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field jacket_address", values[i])
			} else if value.Valid {
				s.JacketAddress = value.String
			}
		case stage.FieldTotalNotes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_notes", values[i])
			} else if value.Valid {
				s.TotalNotes = int(value.Int64)
			}
		case stage.FieldMaxCombo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_combo", values[i])
			} else if value.Valid {
				s.MaxCombo = int(value.Int64)
			}
		case stage.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				s.IsActive = value.Bool
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Stage.
// This includes values selected through modifiers, order, etc.
func (s *Stage) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryMusic queries the "music" edge of the Stage entity.
func (s *Stage) QueryMusic() *MusicQuery {
	return NewStageClient(s.config).QueryMusic(s)
}

// QueryRecords queries the "records" edge of the Stage entity.
func (s *Stage) QueryRecords() *RecordQuery {
	return NewStageClient(s.config).QueryRecords(s)
}

// Update returns a builder for updating this Stage.
// Note that you need to call Stage.Unwrap() before calling this method if this Stage
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Stage) Update() *StageUpdateOne {
	return NewStageClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Stage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Stage) Unwrap() *Stage {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Stage is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Stage) String() string {
	var builder strings.Builder
	builder.WriteString("Stage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("music_id=")
	builder.WriteString(fmt.Sprintf("%v", s.MusicID))
	builder.WriteString(", ")
	builder.WriteString("level_name=")
	builder.WriteString(s.LevelName)
	builder.WriteString(", ")
	builder.WriteString("difficulty=")
	builder.WriteString(fmt.Sprintf("%v", s.Difficulty))
	builder.WriteString(", ")
	builder.WriteString("level_address=")
	builder.WriteString(s.LevelAddress)
	builder.WriteString(", ")
	builder.WriteString("jacket_address=")
	builder.WriteString(s.JacketAddress)
	builder.WriteString(", ")
	builder.WriteString("total_notes=")
	builder.WriteString(fmt.Sprintf("%v", s.TotalNotes))
	builder.WriteString(", ")
	builder.WriteString("max_combo=")
	builder.WriteString(fmt.Sprintf("%v", s.MaxCombo))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", s.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// Stages is a parsable slice of Stage.
type Stages []*Stage
