// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/music"
	"github.com/witchs-lounge_backend/ent/record"
	"github.com/witchs-lounge_backend/ent/stage"
)

// StageCreate is the builder for creating a Stage entity.
type StageCreate struct {
	config
	mutation *StageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sc *StageCreate) SetCreatedAt(t time.Time) *StageCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *StageCreate) SetNillableCreatedAt(t *time.Time) *StageCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *StageCreate) SetUpdatedAt(t time.Time) *StageCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *StageCreate) SetNillableUpdatedAt(t *time.Time) *StageCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetMusicID sets the "music_id" field.
func (sc *StageCreate) SetMusicID(u uuid.UUID) *StageCreate {
	sc.mutation.SetMusicID(u)
	return sc
}

// SetLevelName sets the "level_name" field.
func (sc *StageCreate) SetLevelName(s string) *StageCreate {
	sc.mutation.SetLevelName(s)
	return sc
}

// SetLevelAddress sets the "level_address" field.
func (sc *StageCreate) SetLevelAddress(s string) *StageCreate {
	sc.mutation.SetLevelAddress(s)
	return sc
}

// SetJacketAddress sets the "jacket_address" field.
func (sc *StageCreate) SetJacketAddress(s string) *StageCreate {
	sc.mutation.SetJacketAddress(s)
	return sc
}

// SetID sets the "id" field.
func (sc *StageCreate) SetID(u uuid.UUID) *StageCreate {
	sc.mutation.SetID(u)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *StageCreate) SetNillableID(u *uuid.UUID) *StageCreate {
	if u != nil {
		sc.SetID(*u)
	}
	return sc
}

// SetMusic sets the "music" edge to the Music entity.
func (sc *StageCreate) SetMusic(m *Music) *StageCreate {
	return sc.SetMusicID(m.ID)
}

// AddRecordIDs adds the "records" edge to the Record entity by IDs.
func (sc *StageCreate) AddRecordIDs(ids ...uuid.UUID) *StageCreate {
	sc.mutation.AddRecordIDs(ids...)
	return sc
}

// AddRecords adds the "records" edges to the Record entity.
func (sc *StageCreate) AddRecords(r ...*Record) *StageCreate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sc.AddRecordIDs(ids...)
}

// Mutation returns the StageMutation object of the builder.
func (sc *StageCreate) Mutation() *StageMutation {
	return sc.mutation
}

// Save creates the Stage in the database.
func (sc *StageCreate) Save(ctx context.Context) (*Stage, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StageCreate) SaveX(ctx context.Context) *Stage {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StageCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StageCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *StageCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := stage.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := stage.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.ID(); !ok {
		v := stage.DefaultID()
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StageCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Stage.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Stage.updated_at"`)}
	}
	if _, ok := sc.mutation.MusicID(); !ok {
		return &ValidationError{Name: "music_id", err: errors.New(`ent: missing required field "Stage.music_id"`)}
	}
	if _, ok := sc.mutation.LevelName(); !ok {
		return &ValidationError{Name: "level_name", err: errors.New(`ent: missing required field "Stage.level_name"`)}
	}
	if v, ok := sc.mutation.LevelName(); ok {
		if err := stage.LevelNameValidator(v); err != nil {
			return &ValidationError{Name: "level_name", err: fmt.Errorf(`ent: validator failed for field "Stage.level_name": %w`, err)}
		}
	}
	if _, ok := sc.mutation.LevelAddress(); !ok {
		return &ValidationError{Name: "level_address", err: errors.New(`ent: missing required field "Stage.level_address"`)}
	}
	if v, ok := sc.mutation.LevelAddress(); ok {
		if err := stage.LevelAddressValidator(v); err != nil {
			return &ValidationError{Name: "level_address", err: fmt.Errorf(`ent: validator failed for field "Stage.level_address": %w`, err)}
		}
	}
	if _, ok := sc.mutation.JacketAddress(); !ok {
		return &ValidationError{Name: "jacket_address", err: errors.New(`ent: missing required field "Stage.jacket_address"`)}
	}
	if v, ok := sc.mutation.JacketAddress(); ok {
		if err := stage.JacketAddressValidator(v); err != nil {
			return &ValidationError{Name: "jacket_address", err: fmt.Errorf(`ent: validator failed for field "Stage.jacket_address": %w`, err)}
		}
	}
	if len(sc.mutation.MusicIDs()) == 0 {
		return &ValidationError{Name: "music", err: errors.New(`ent: missing required edge "Stage.music"`)}
	}
	return nil
}

func (sc *StageCreate) sqlSave(ctx context.Context) (*Stage, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StageCreate) createSpec() (*Stage, *sqlgraph.CreateSpec) {
	var (
		_node = &Stage{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(stage.Table, sqlgraph.NewFieldSpec(stage.FieldID, field.TypeUUID))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(stage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(stage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.LevelName(); ok {
		_spec.SetField(stage.FieldLevelName, field.TypeString, value)
		_node.LevelName = value
	}
	if value, ok := sc.mutation.LevelAddress(); ok {
		_spec.SetField(stage.FieldLevelAddress, field.TypeString, value)
		_node.LevelAddress = value
	}
	if value, ok := sc.mutation.JacketAddress(); ok {
		_spec.SetField(stage.FieldJacketAddress, field.TypeString, value)
		_node.JacketAddress = value
	}
	if nodes := sc.mutation.MusicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.MusicTable,
			Columns: []string{stage.MusicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(music.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MusicID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.RecordsTable,
			Columns: []string{stage.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StageCreateBulk is the builder for creating many Stage entities in bulk.
type StageCreateBulk struct {
	config
	err      error
	builders []*StageCreate
}

// Save creates the Stage entities in the database.
func (scb *StageCreateBulk) Save(ctx context.Context) ([]*Stage, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Stage, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StageCreateBulk) SaveX(ctx context.Context) []*Stage {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StageCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StageCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
