// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/product"
	"github.com/witchs-lounge_backend/ent/user"
	"github.com/witchs-lounge_backend/ent/userpurchase"
)

// UserPurchaseCreate is the builder for creating a UserPurchase entity.
type UserPurchaseCreate struct {
	config
	mutation *UserPurchaseMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (upc *UserPurchaseCreate) SetUserID(u uuid.UUID) *UserPurchaseCreate {
	upc.mutation.SetUserID(u)
	return upc
}

// SetProductID sets the "product_id" field.
func (upc *UserPurchaseCreate) SetProductID(u uuid.UUID) *UserPurchaseCreate {
	upc.mutation.SetProductID(u)
	return upc
}

// SetPurchaseDate sets the "purchase_date" field.
func (upc *UserPurchaseCreate) SetPurchaseDate(t time.Time) *UserPurchaseCreate {
	upc.mutation.SetPurchaseDate(t)
	return upc
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (upc *UserPurchaseCreate) SetNillablePurchaseDate(t *time.Time) *UserPurchaseCreate {
	if t != nil {
		upc.SetPurchaseDate(*t)
	}
	return upc
}

// SetID sets the "id" field.
func (upc *UserPurchaseCreate) SetID(u uuid.UUID) *UserPurchaseCreate {
	upc.mutation.SetID(u)
	return upc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (upc *UserPurchaseCreate) SetNillableID(u *uuid.UUID) *UserPurchaseCreate {
	if u != nil {
		upc.SetID(*u)
	}
	return upc
}

// SetUser sets the "user" edge to the User entity.
func (upc *UserPurchaseCreate) SetUser(u *User) *UserPurchaseCreate {
	return upc.SetUserID(u.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (upc *UserPurchaseCreate) SetProduct(p *Product) *UserPurchaseCreate {
	return upc.SetProductID(p.ID)
}

// Mutation returns the UserPurchaseMutation object of the builder.
func (upc *UserPurchaseCreate) Mutation() *UserPurchaseMutation {
	return upc.mutation
}

// Save creates the UserPurchase in the database.
func (upc *UserPurchaseCreate) Save(ctx context.Context) (*UserPurchase, error) {
	upc.defaults()
	return withHooks(ctx, upc.sqlSave, upc.mutation, upc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (upc *UserPurchaseCreate) SaveX(ctx context.Context) *UserPurchase {
	v, err := upc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upc *UserPurchaseCreate) Exec(ctx context.Context) error {
	_, err := upc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upc *UserPurchaseCreate) ExecX(ctx context.Context) {
	if err := upc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (upc *UserPurchaseCreate) defaults() {
	if _, ok := upc.mutation.PurchaseDate(); !ok {
		v := userpurchase.DefaultPurchaseDate()
		upc.mutation.SetPurchaseDate(v)
	}
	if _, ok := upc.mutation.ID(); !ok {
		v := userpurchase.DefaultID()
		upc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upc *UserPurchaseCreate) check() error {
	if _, ok := upc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPurchase.user_id"`)}
	}
	if _, ok := upc.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "UserPurchase.product_id"`)}
	}
	if _, ok := upc.mutation.PurchaseDate(); !ok {
		return &ValidationError{Name: "purchase_date", err: errors.New(`ent: missing required field "UserPurchase.purchase_date"`)}
	}
	if len(upc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserPurchase.user"`)}
	}
	if len(upc.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "UserPurchase.product"`)}
	}
	return nil
}

func (upc *UserPurchaseCreate) sqlSave(ctx context.Context) (*UserPurchase, error) {
	if err := upc.check(); err != nil {
		return nil, err
	}
	_node, _spec := upc.createSpec()
	if err := sqlgraph.CreateNode(ctx, upc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	upc.mutation.id = &_node.ID
	upc.mutation.done = true
	return _node, nil
}

func (upc *UserPurchaseCreate) createSpec() (*UserPurchase, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPurchase{config: upc.config}
		_spec = sqlgraph.NewCreateSpec(userpurchase.Table, sqlgraph.NewFieldSpec(userpurchase.FieldID, field.TypeUUID))
	)
	if id, ok := upc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := upc.mutation.PurchaseDate(); ok {
		_spec.SetField(userpurchase.FieldPurchaseDate, field.TypeTime, value)
		_node.PurchaseDate = value
	}
	if nodes := upc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userpurchase.UserTable,
			Columns: []string{userpurchase.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := upc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userpurchase.ProductTable,
			Columns: []string{userpurchase.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserPurchaseCreateBulk is the builder for creating many UserPurchase entities in bulk.
type UserPurchaseCreateBulk struct {
	config
	err      error
	builders []*UserPurchaseCreate
}

// Save creates the UserPurchase entities in the database.
func (upcb *UserPurchaseCreateBulk) Save(ctx context.Context) ([]*UserPurchase, error) {
	if upcb.err != nil {
		return nil, upcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(upcb.builders))
	nodes := make([]*UserPurchase, len(upcb.builders))
	mutators := make([]Mutator, len(upcb.builders))
	for i := range upcb.builders {
		func(i int, root context.Context) {
			builder := upcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPurchaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, upcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, upcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, upcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (upcb *UserPurchaseCreateBulk) SaveX(ctx context.Context) []*UserPurchase {
	v, err := upcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upcb *UserPurchaseCreateBulk) Exec(ctx context.Context) error {
	_, err := upcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upcb *UserPurchaseCreateBulk) ExecX(ctx context.Context) {
	if err := upcb.Exec(ctx); err != nil {
		panic(err)
	}
}
