// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/achievement"
	"github.com/witchs-lounge_backend/ent/predicate"
	"github.com/witchs-lounge_backend/ent/user"
	"github.com/witchs-lounge_backend/ent/userachievement"
)

// UserAchievementQuery is the builder for querying UserAchievement entities.
type UserAchievementQuery struct {
	config
	ctx             *QueryContext
	order           []userachievement.OrderOption
	inters          []Interceptor
	predicates      []predicate.UserAchievement
	withUser        *UserQuery
	withAchievement *AchievementQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserAchievementQuery builder.
func (uaq *UserAchievementQuery) Where(ps ...predicate.UserAchievement) *UserAchievementQuery {
	uaq.predicates = append(uaq.predicates, ps...)
	return uaq
}

// Limit the number of records to be returned by this query.
func (uaq *UserAchievementQuery) Limit(limit int) *UserAchievementQuery {
	uaq.ctx.Limit = &limit
	return uaq
}

// Offset to start from.
func (uaq *UserAchievementQuery) Offset(offset int) *UserAchievementQuery {
	uaq.ctx.Offset = &offset
	return uaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uaq *UserAchievementQuery) Unique(unique bool) *UserAchievementQuery {
	uaq.ctx.Unique = &unique
	return uaq
}

// Order specifies how the records should be ordered.
func (uaq *UserAchievementQuery) Order(o ...userachievement.OrderOption) *UserAchievementQuery {
	uaq.order = append(uaq.order, o...)
	return uaq
}

// QueryUser chains the current query on the "user" edge.
func (uaq *UserAchievementQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: uaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userachievement.Table, userachievement.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userachievement.UserTable, userachievement.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAchievement chains the current query on the "achievement" edge.
func (uaq *UserAchievementQuery) QueryAchievement() *AchievementQuery {
	query := (&AchievementClient{config: uaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userachievement.Table, userachievement.FieldID, selector),
			sqlgraph.To(achievement.Table, achievement.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userachievement.AchievementTable, userachievement.AchievementColumn),
		)
		fromU = sqlgraph.SetNeighbors(uaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserAchievement entity from the query.
// Returns a *NotFoundError when no UserAchievement was found.
func (uaq *UserAchievementQuery) First(ctx context.Context) (*UserAchievement, error) {
	nodes, err := uaq.Limit(1).All(setContextOp(ctx, uaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userachievement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uaq *UserAchievementQuery) FirstX(ctx context.Context) *UserAchievement {
	node, err := uaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserAchievement ID from the query.
// Returns a *NotFoundError when no UserAchievement ID was found.
func (uaq *UserAchievementQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uaq.Limit(1).IDs(setContextOp(ctx, uaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userachievement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uaq *UserAchievementQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := uaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserAchievement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserAchievement entity is found.
// Returns a *NotFoundError when no UserAchievement entities are found.
func (uaq *UserAchievementQuery) Only(ctx context.Context) (*UserAchievement, error) {
	nodes, err := uaq.Limit(2).All(setContextOp(ctx, uaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userachievement.Label}
	default:
		return nil, &NotSingularError{userachievement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uaq *UserAchievementQuery) OnlyX(ctx context.Context) *UserAchievement {
	node, err := uaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserAchievement ID in the query.
// Returns a *NotSingularError when more than one UserAchievement ID is found.
// Returns a *NotFoundError when no entities are found.
func (uaq *UserAchievementQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uaq.Limit(2).IDs(setContextOp(ctx, uaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userachievement.Label}
	default:
		err = &NotSingularError{userachievement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uaq *UserAchievementQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := uaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserAchievements.
func (uaq *UserAchievementQuery) All(ctx context.Context) ([]*UserAchievement, error) {
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryAll)
	if err := uaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserAchievement, *UserAchievementQuery]()
	return withInterceptors[[]*UserAchievement](ctx, uaq, qr, uaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uaq *UserAchievementQuery) AllX(ctx context.Context) []*UserAchievement {
	nodes, err := uaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserAchievement IDs.
func (uaq *UserAchievementQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if uaq.ctx.Unique == nil && uaq.path != nil {
		uaq.Unique(true)
	}
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryIDs)
	if err = uaq.Select(userachievement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uaq *UserAchievementQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := uaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uaq *UserAchievementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryCount)
	if err := uaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uaq, querierCount[*UserAchievementQuery](), uaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uaq *UserAchievementQuery) CountX(ctx context.Context) int {
	count, err := uaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uaq *UserAchievementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryExist)
	switch _, err := uaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uaq *UserAchievementQuery) ExistX(ctx context.Context) bool {
	exist, err := uaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserAchievementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uaq *UserAchievementQuery) Clone() *UserAchievementQuery {
	if uaq == nil {
		return nil
	}
	return &UserAchievementQuery{
		config:          uaq.config,
		ctx:             uaq.ctx.Clone(),
		order:           append([]userachievement.OrderOption{}, uaq.order...),
		inters:          append([]Interceptor{}, uaq.inters...),
		predicates:      append([]predicate.UserAchievement{}, uaq.predicates...),
		withUser:        uaq.withUser.Clone(),
		withAchievement: uaq.withAchievement.Clone(),
		// clone intermediate query.
		sql:  uaq.sql.Clone(),
		path: uaq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uaq *UserAchievementQuery) WithUser(opts ...func(*UserQuery)) *UserAchievementQuery {
	query := (&UserClient{config: uaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uaq.withUser = query
	return uaq
}

// WithAchievement tells the query-builder to eager-load the nodes that are connected to
// the "achievement" edge. The optional arguments are used to configure the query builder of the edge.
func (uaq *UserAchievementQuery) WithAchievement(opts ...func(*AchievementQuery)) *UserAchievementQuery {
	query := (&AchievementClient{config: uaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uaq.withAchievement = query
	return uaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserAchievement.Query().
//		GroupBy(userachievement.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uaq *UserAchievementQuery) GroupBy(field string, fields ...string) *UserAchievementGroupBy {
	uaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserAchievementGroupBy{build: uaq}
	grbuild.flds = &uaq.ctx.Fields
	grbuild.label = userachievement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UserAchievement.Query().
//		Select(userachievement.FieldCreatedAt).
//		Scan(ctx, &v)
func (uaq *UserAchievementQuery) Select(fields ...string) *UserAchievementSelect {
	uaq.ctx.Fields = append(uaq.ctx.Fields, fields...)
	sbuild := &UserAchievementSelect{UserAchievementQuery: uaq}
	sbuild.label = userachievement.Label
	sbuild.flds, sbuild.scan = &uaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserAchievementSelect configured with the given aggregations.
func (uaq *UserAchievementQuery) Aggregate(fns ...AggregateFunc) *UserAchievementSelect {
	return uaq.Select().Aggregate(fns...)
}

func (uaq *UserAchievementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uaq); err != nil {
				return err
			}
		}
	}
	for _, f := range uaq.ctx.Fields {
		if !userachievement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uaq.path != nil {
		prev, err := uaq.path(ctx)
		if err != nil {
			return err
		}
		uaq.sql = prev
	}
	return nil
}

func (uaq *UserAchievementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserAchievement, error) {
	var (
		nodes       = []*UserAchievement{}
		_spec       = uaq.querySpec()
		loadedTypes = [2]bool{
			uaq.withUser != nil,
			uaq.withAchievement != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserAchievement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserAchievement{config: uaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uaq.withUser; query != nil {
		if err := uaq.loadUser(ctx, query, nodes, nil,
			func(n *UserAchievement, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := uaq.withAchievement; query != nil {
		if err := uaq.loadAchievement(ctx, query, nodes, nil,
			func(n *UserAchievement, e *Achievement) { n.Edges.Achievement = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uaq *UserAchievementQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserAchievement, init func(*UserAchievement), assign func(*UserAchievement, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserAchievement)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (uaq *UserAchievementQuery) loadAchievement(ctx context.Context, query *AchievementQuery, nodes []*UserAchievement, init func(*UserAchievement), assign func(*UserAchievement, *Achievement)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserAchievement)
	for i := range nodes {
		fk := nodes[i].AchievementID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(achievement.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "achievement_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uaq *UserAchievementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uaq.querySpec()
	_spec.Node.Columns = uaq.ctx.Fields
	if len(uaq.ctx.Fields) > 0 {
		_spec.Unique = uaq.ctx.Unique != nil && *uaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uaq.driver, _spec)
}

func (uaq *UserAchievementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userachievement.Table, userachievement.Columns, sqlgraph.NewFieldSpec(userachievement.FieldID, field.TypeUUID))
	_spec.From = uaq.sql
	if unique := uaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uaq.path != nil {
		_spec.Unique = true
	}
	if fields := uaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userachievement.FieldID)
		for i := range fields {
			if fields[i] != userachievement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if uaq.withUser != nil {
			_spec.Node.AddColumnOnce(userachievement.FieldUserID)
		}
		if uaq.withAchievement != nil {
			_spec.Node.AddColumnOnce(userachievement.FieldAchievementID)
		}
	}
	if ps := uaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uaq *UserAchievementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uaq.driver.Dialect())
	t1 := builder.Table(userachievement.Table)
	columns := uaq.ctx.Fields
	if len(columns) == 0 {
		columns = userachievement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uaq.sql != nil {
		selector = uaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uaq.ctx.Unique != nil && *uaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uaq.predicates {
		p(selector)
	}
	for _, p := range uaq.order {
		p(selector)
	}
	if offset := uaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserAchievementGroupBy is the group-by builder for UserAchievement entities.
type UserAchievementGroupBy struct {
	selector
	build *UserAchievementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uagb *UserAchievementGroupBy) Aggregate(fns ...AggregateFunc) *UserAchievementGroupBy {
	uagb.fns = append(uagb.fns, fns...)
	return uagb
}

// Scan applies the selector query and scans the result into the given value.
func (uagb *UserAchievementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uagb.build.ctx, ent.OpQueryGroupBy)
	if err := uagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAchievementQuery, *UserAchievementGroupBy](ctx, uagb.build, uagb, uagb.build.inters, v)
}

func (uagb *UserAchievementGroupBy) sqlScan(ctx context.Context, root *UserAchievementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uagb.fns))
	for _, fn := range uagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uagb.flds)+len(uagb.fns))
		for _, f := range *uagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserAchievementSelect is the builder for selecting fields of UserAchievement entities.
type UserAchievementSelect struct {
	*UserAchievementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uas *UserAchievementSelect) Aggregate(fns ...AggregateFunc) *UserAchievementSelect {
	uas.fns = append(uas.fns, fns...)
	return uas
}

// Scan applies the selector query and scans the result into the given value.
func (uas *UserAchievementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uas.ctx, ent.OpQuerySelect)
	if err := uas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAchievementQuery, *UserAchievementSelect](ctx, uas.UserAchievementQuery, uas, uas.inters, v)
}

func (uas *UserAchievementSelect) sqlScan(ctx context.Context, root *UserAchievementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uas.fns))
	for _, fn := range uas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
