name: Deploy Backend

on:
  push:
    branches:
      - main  # 또는 배포용 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kjw2262/witchs_lounge_backend:latest

      # SSH로 원격 서버 접속 후 compose pull & up
      - name: Deploy to Windows Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.WINDOWS_HOST }}
          username: ${{ secrets.WINDOWS_USER }}
          key: ${{ secrets.WINDOWS_SSH_KEY }}
          script: |
            cd C:\path\to\project
            docker compose pull
            docker compose up -d --remove-orphans